### ISSUE TITLE
prefix not working as expected?

### ISSUE THREAD

**Issue by coderofsalvation** [fortunejs/fortune-json-api#33] opened 2016-08-21 09:07 UTC
given this config:

```
    serializers: [
      {
        type: 'fortune-json-api',
        options: {}
      }
    ]
```

produces this test:

```
  $ curl "http://localhost:1880/users"
  {"meta":{"count":0},"links":{"self":"/users"},"data":[]}
```

however this config (note the prefix):

```
    serializers: [
      {
        type: 'fortune-json-api',
        options: {prefix:"api"}
      }
    ]
```

produces this:

```
  $ curl "http://localhost:1880/api/users"
  {"jsonapi":{"version":"1.0"},"errors":[{"title":"NotFoundError: The requested type \"api\" is note a valid type.","detail":":[","code":1}]}
  {"meta":{"count":0},"links":{"self":"api/users"},"data":[]}

  $ curl "http://localhost:1880/users"
  {"meta":{"count":0},"links":{"self":"api/users"},"data":[]}
```

> note the second curl-call: the api thinks it's being served at 'api/users' while in reality it isn't?

**Comment by gr0uch** [comment] 2016-08-21 20:12
The problem is in exactly this line: https://github.com/fortunejs/fortune-json-api/blob/88b98a43b2f5b819c84334e5acc8afd98c1f2ceb/lib/helpers.js#L60

The request URL needs to have the prefix stripped before trying to parse it.

Addendum: the prefix option should work if Fortune is mounted as a middleware in Connect/Express because it mutates the request URL internally.

**Comment by coderofsalvation** [comment] 2016-08-30 07:51
aha!
Im not using express/connect.
Thx for noticing, in that case I will add some middleware code which will mutate the request url.

**Comment by gr0uch** [comment] 2016-08-30 08:04
regardless of whether one is using express/connect, it _should_ be patched so that it also works out of the box. the fix should be fairly straightforward and also be compatible with express middleware.

**Comment by gr0uch** [comment] 2016-09-05 22:55
Should be fixed in https://github.com/fortunejs/fortune-json-api/commit/4ff3c09153c9580042c0a983cd1a64ca167a75d2.

**Closed as completed by gr0uch** 2016-09-05 22:55 UTC

**Comment by hamez0r** [comment] 2019-08-23 12:23
Is this issue fixed? I'm experiencing a similar behavior in 2.2.0, only this time the API replies to both endpoints.

### Configuration
```
  const listener = fortuneHTTP(store, {
    serializers: [
      [ jsonApiSerializer, { prefix: 'api' } ]
    ]
  });
```

### Behavior
```
curl "http://localhost:3000/users"                                                                                   
{
  "jsonapi": {
    "version": "1.0"
  },
  "meta": {
    "count": 0
  },
  "links": {
    "self": "/api/users"
  },
  "data": []
}

curl "http://localhost:3000/api/users"   
{
  "jsonapi": {
    "version": "1.0"
  },
  "meta": {
    "count": 0
  },
  "links": {
    "self": "/api/users"
  },
  "data": []
}
```

**Comment by gr0uch** [comment] 2019-08-23 18:22
@hamez0r this may be an unintended side effect of the implementation: it actually rewrites the route without the prefix, so it responds to with or without prefix.

**Comment by hamez0r** [comment] 2019-08-25 19:20
@daliwali any chance for this to be fixed? The behavior is not ideal.
I'm not sure whether removing that if clause would have any other side effect.
