### ISSUE TITLE
Attribute in PATCH does not get updated/saved

### ISSUE THREAD

**Issue by nickschot** [fortunejs/fortune-json-api#4] opened 2015-10-10 22:29 UTC
I'm throwing the following payload at the latest fortune w/ JSON-API and mongodb:

```
{  
   "data":{  
      "id":"c52843063cb9fa933e422e24b6059872",
      "attributes":{  
         "name":"New Name"
      },
      "type":"forms"
   }
}
```

And get the following response back (the name attribute did not get updated):

```
{  
   "links":{  
      "self":"http://localhost/forms/c52843063cb9fa933e422e24b6059872"
   },
   "data":{  
      "type":"forms",
      "id":"c52843063cb9fa933e422e24b6059872",
      "attributes":{  
         "name":"Old Name",
      },
      "relationships":{  
        ............
      },
      "links":{  
         "self":"http://localhost/forms/c52843063cb9fa933e422e24b6059872"
      }
   }
}
```

The name attribute is defined as a String type in the form model. Setting it works fine with a CREATE instead of a PATCH.

**Comment by nickschot** [comment] 2015-10-11 16:44
As of today I'm also getting the following error (with the same request/response)

```
{"errors":[{"title":"BadRequestError","detail":"Multiple records can not have the same to-one link value on the field \"questions\"."}]}
```

Busy investigating further...

**Comment by gr0uch** [comment] 2015-11-02 10:26
Any update on this? Possible problem in `parseUpdate`.

**Comment by nickschot** [comment] 2015-11-02 10:33
Unfortunately I haven't had enough time yet to look further into this. I've planned to thoroughly look into it next week.

**Comment by nickschot** [comment] 2015-12-09 14:45
Just updated all my server dependencies. Will check if the issue still occurs.

**Comment by gr0uch** [comment] 2015-12-29 22:22
Closing since I can't reproduce the issue.

**Closed as completed by gr0uch** 2015-12-29 22:22 UTC
